- name: Installing Docker pre-requisites
  yum:
    name: "{{item}}"
    state: latest
  with_items: 
       - "yum-utils"
       - "device-mapper-persistent-data"
       - "lvm2"
  become: yes
  become_user: root

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
  become: yes

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: yes

- name: Install docker-py
  pip: name=docker-py version=1.9.0

- name: Creating sonarqube directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/sonarqube

- name: Pull the latest official sonarqube docker image
  become: yes
  become_method: sudo
  become_user: root
  docker_image:
    name=sonarqube:latest
    state=present
    force=yes

- name: Create a container from the sonarqube docker image
  become: yes
  become_method: sudo
  become_user: root
  docker_container:
    name: "sonarqube"
    image: "sonarqube"
    ports:
        - "9000:9000"
        - "9092:9092"
    volumes:
        - "/share/sonarqube:/var/sonarqube_home"
    state: present
    recreate: no

- name: Copy systemd service script to start and stop the sonarqube container
  become: yes
  become_method: sudo
  become_user: root
  copy: src=files/sonarqube.service dest=/etc/systemd/system

- name: Reload systemctl
  become: yes
  become_method: sudo
  become_user: root
  shell: systemctl reload-or-restart sonarqube

- name: Enable the docker-sonarqube service
  become: yes
  become_method: sudo
  become_user: root
  shell: systemctl enable sonarqube
